platform :ios, '10.0'

target 'notes' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  target 'notesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
